name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/wisecow:$IMAGE_TAG .
        docker push $ECR_REGISTRY/wisecow:$IMAGE_TAG
        
    - name: Deploy to Kubernetes
      env:
        KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        kubectl config set-cluster default-cluster --server=$KUBE_SERVER
        kubectl config set-credentials default-user --token=$KUBE_TOKEN
        kubectl config set-context default-context --cluster=default-cluster --user=default-user
        kubectl config use-context default-context
        kubectl set image deployment/wisecow wisecow=$ECR_REGISTRY/wisecow:$IMAGE_TAG
        kubectl rollout status deployment/wisecow
