name: Build, Push Docker Image, and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment to run the job on

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (or your preferred container registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password (or token) from secrets

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow:latest .

      # Step 5: Push Docker image to Docker Hub (or any registry)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

  deploy:
    needs: build  # Ensure the build job completes before deploying
    runs-on: ubuntu-latest  # The environment to run the job on
    steps:
      # Step 6: List files in the k8s directory for debugging
      - name: List files in k8s directory
        run: |
          ls -al k8s/

      # Step 7: Update the wisecow-deployment.yaml with the new image tag
      - name: Update wisecow-deployment.yaml with new image tag
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/wisecow:latest"
          sed -i "s|image:.*|image: $IMAGE_TAG|g" k8s/wisecow-deployment.yaml

      # Step 8: Set up kubectl and update kubeconfig
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}

      # Step 9: Apply Kubernetes deployment
      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f k8s/wisecow-deployment.yaml
          kubectl apply -f k8s/wisecow-service.yaml
