name: Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker Image
        run: docker build -t 490004613642.dkr.ecr.ap-south-1.amazonaws.com/wisecow:latest .

      - name: Login to ECR
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Push the Docker Image
        run: docker push 490004613642.dkr.ecr.ap-south-1.amazonaws.com/wisecow:latest

      - name: Deploy to Kubernetes
        uses: actions/deployment/deploy-action@v1
        with:
          repository-owner: your-username
          repository-name: your-repo-name
          token: ${{ secrets.GITHUB_TOKEN }}
          file: deployment.yaml
          kubecontext: your-cluster-context  # Replace with your cluster context

# Replace these placeholders:
#   - your-username: Your GitHub username
#   - your-repo-name: Your repository name
#   - your-cluster-context: Name of your Kubernetes cluster context (from kubeconfig)
